// AUTO-GENERATED by generate.mjs — do not edit by hand.
import { LitElementStateService } from '../../src/index';
import { PerfState } from './state';

declare const s: LitElementStateService<PerfState>;

s.subscribe(['root', 'tag0'], v => {}); // 0
s.subscribe(['root', 'flag0'], v => {}); // 1
s.subscribe(['root', 'opt0'], v => {}); // 2
s.get(['root', 'tag0']); // 3
s.subscribe(['root', 'next0', 'tag1'], v => {}); // 4
s.subscribe(['root', 'next0', 'flag1'], v => {}); // 5
s.subscribe(['root', 'next0', 'opt1'], v => {}); // 6
s.get(['root', 'next0', 'tag1']); // 7
s.subscribe(['root', 'next0', 'next1', 'tag2'], v => {}); // 8
s.subscribe(['root', 'next0', 'next1', 'flag2'], v => {}); // 9
s.subscribe(['root', 'next0', 'next1', 'opt2'], v => {}); // 10
s.get(['root', 'next0', 'next1', 'tag2']); // 11
s.subscribe(['root', 'next0', 'next1', 'next2', 'tag3'], v => {}); // 12
s.subscribe(['root', 'next0', 'next1', 'next2', 'flag3'], v => {}); // 13
s.subscribe(['root', 'next0', 'next1', 'next2', 'opt3'], v => {}); // 14
s.get(['root', 'next0', 'next1', 'next2', 'tag3']); // 15
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'tag4'], v => {}); // 16
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'flag4'], v => {}); // 17
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'opt4'], v => {}); // 18
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'tag4']); // 19
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'tag5'], v => {}); // 20
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'flag5'], v => {}); // 21
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'opt5'], v => {}); // 22
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'tag5']); // 23
s.subscribe(['root', { array: 'items0', get: 0 }], v => {}); // 24
s.subscribe(['root', { array: 'items0', get: (e: { id: number }, i?: number) => e.id === i }], v => {}); // 25
s.get(['root', { array: 'items0', get: 0 }, 'name']); // 26
s.subscribe(['root', { array: 'roItems0', get: 0 }], v => {}); // 27
s.subscribe(['root', 'dict0', 'anykey'], v => {}); // 28
s.subscribe(['root', 'items0'], v => {}); // 29
s.subscribe(['root', 'union0', 'shared'], v => {}); // 30
s.subscribe(['root', 'next0', { array: 'items1', get: 0 }], v => {}); // 31
s.subscribe(['root', 'next0', { array: 'items1', get: (e: { id: number }, i?: number) => e.id === i }], v => {}); // 32
s.get(['root', 'next0', { array: 'items1', get: 0 }, 'name']); // 33
s.subscribe(['root', 'next0', { array: 'roItems1', get: 0 }], v => {}); // 34
s.subscribe(['root', 'next0', 'dict1', 'anykey'], v => {}); // 35
s.subscribe(['root', 'next0', 'items1'], v => {}); // 36
s.subscribe(['root', 'next0', 'union1', 'shared'], v => {}); // 37
s.subscribe(['root', 'next0', 'next1', { array: 'items2', get: 0 }], v => {}); // 38
s.subscribe(['root', 'next0', 'next1', { array: 'items2', get: (e: { id: number }, i?: number) => e.id === i }], v => {}); // 39
s.get(['root', 'next0', 'next1', { array: 'items2', get: 0 }, 'name']); // 40
s.subscribe(['root', 'next0', 'next1', { array: 'roItems2', get: 0 }], v => {}); // 41
s.subscribe(['root', 'next0', 'next1', 'dict2', 'anykey'], v => {}); // 42
s.subscribe(['root', 'next0', 'next1', 'items2'], v => {}); // 43
s.subscribe(['root', 'next0', 'next1', 'union2', 'shared'], v => {}); // 44
s.subscribe(['root', 'next0', 'next1', 'next2', { array: 'items3', get: 0 }], v => {}); // 45
s.subscribe(['root', 'next0', 'next1', 'next2', { array: 'items3', get: (e: { id: number }, i?: number) => e.id === i }], v => {}); // 46
s.get(['root', 'next0', 'next1', 'next2', { array: 'items3', get: 0 }, 'name']); // 47
s.subscribe(['root', 'next0', 'next1', 'next2', { array: 'roItems3', get: 0 }], v => {}); // 48
s.subscribe(['root', 'next0', 'next1', 'next2', 'dict3', 'anykey'], v => {}); // 49
s.subscribe(['root', 'next0', 'next1', 'next2', 'items3'], v => {}); // 50
s.subscribe(['root', 'next0', 'next1', 'next2', 'union3', 'shared'], v => {}); // 51
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: 0 }], v => {}); // 52
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: (e: { id: number }, i?: number) => e.id === i }], v => {}); // 53
s.get(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: 0 }, 'name']); // 54
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', { array: 'roItems4', get: 0 }], v => {}); // 55
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'dict4', 'anykey'], v => {}); // 56
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'items4'], v => {}); // 57
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'union4', 'shared'], v => {}); // 58
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'items5', get: 0 }], v => {}); // 59
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'items5', get: (e: { id: number }, i?: number) => e.id === i }], v => {}); // 60
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'items5', get: 0 }, 'name']); // 61
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'roItems5', get: 0 }], v => {}); // 62
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'dict5', 'anykey'], v => {}); // 63
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'items5'], v => {}); // 64
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'union5', 'shared'], v => {}); // 65
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'next5', 'tag6']); // 66
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'next5', 'next6', 'tag7']); // 67
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'next5', 'next6', 'next7', 'tag8']); // 68
s.subscribe(['root', { array: 'items0', get: 0 }, { array: 'children', get: 0 }, 'name'], v => {}); // 69
s.subscribe(['root', 'next0', { array: 'items1', get: 0 }, { array: 'children', get: 0 }, 'name'], v => {}); // 70
s.subscribe(['root', 'next0', 'next1', { array: 'items2', get: 0 }, { array: 'children', get: 0 }, 'name'], v => {}); // 71
s.subscribe(['root', 'next0', 'next1', 'next2', { array: 'items3', get: 0 }, { array: 'children', get: 0 }, 'name'], v => {}); // 72
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: 0 }, { array: 'children', get: 0 }, 'name'], v => {}); // 73
s.get(['root', { array: 'items0', get: 0 }, 'leaf', 'label']); // 74
s.get(['root', { array: 'roItems0', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // 75
s.get(['root', 'dict0', 'k', 'leaf', 'note']); // 76
s.subscribe(['root', 'union0', 'kind'], v => {}); // 77
s.get(['root', 'next0', { array: 'items1', get: 0 }, 'leaf', 'label']); // 78
s.get(['root', 'next0', { array: 'roItems1', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // 79
s.get(['root', 'next0', 'dict1', 'k', 'leaf', 'note']); // 80
s.subscribe(['root', 'next0', 'union1', 'kind'], v => {}); // 81
s.get(['root', 'next0', 'next1', { array: 'items2', get: 0 }, 'leaf', 'label']); // 82
s.get(['root', 'next0', 'next1', { array: 'roItems2', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // 83
s.get(['root', 'next0', 'next1', 'dict2', 'k', 'leaf', 'note']); // 84
s.subscribe(['root', 'next0', 'next1', 'union2', 'kind'], v => {}); // 85
s.get(['root', 'next0', 'next1', 'next2', { array: 'items3', get: 0 }, 'leaf', 'label']); // 86
s.get(['root', 'next0', 'next1', 'next2', { array: 'roItems3', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // 87
s.get(['root', 'next0', 'next1', 'next2', 'dict3', 'k', 'leaf', 'note']); // 88
s.subscribe(['root', 'next0', 'next1', 'next2', 'union3', 'kind'], v => {}); // 89
s.get(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: 0 }, 'leaf', 'label']); // 90
s.get(['root', 'next0', 'next1', 'next2', 'next3', { array: 'roItems4', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // 91
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'dict4', 'k', 'leaf', 'note']); // 92
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'union4', 'kind'], v => {}); // 93
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'items5', get: 0 }, 'leaf', 'label']); // 94
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'roItems5', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // 95
s.get(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'dict5', 'k', 'leaf', 'note']); // 96
s.subscribe(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'union5', 'kind'], v => {}); // 97

import { LitElementStateful } from '../../src/index';
class PerfComp extends LitElementStateful<PerfState> {
    p: any;
    run() {
        this.subscribeState(['root', 'tag0'], v => {}); // 98
        this.subscribeState(['root', { array: 'items0', get: 0 }, 'name'], v => {}); // 99
        this.connectState(['root', 'flag0'], 'p'); // 100
        this.connectState(['root', { array: 'items0', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // 101
        this.subscribeState(['root', 'next0', 'tag1'], v => {}); // 102
        this.subscribeState(['root', 'next0', { array: 'items1', get: 0 }, 'name'], v => {}); // 103
        this.connectState(['root', 'next0', 'flag1'], 'p'); // 104
        this.connectState(['root', 'next0', { array: 'items1', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // 105
        this.subscribeState(['root', 'next0', 'next1', 'tag2'], v => {}); // 106
        this.subscribeState(['root', 'next0', 'next1', { array: 'items2', get: 0 }, 'name'], v => {}); // 107
        this.connectState(['root', 'next0', 'next1', 'flag2'], 'p'); // 108
        this.connectState(['root', 'next0', 'next1', { array: 'items2', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // 109
        this.subscribeState(['root', 'next0', 'next1', 'next2', 'tag3'], v => {}); // 110
        this.subscribeState(['root', 'next0', 'next1', 'next2', { array: 'items3', get: 0 }, 'name'], v => {}); // 111
        this.connectState(['root', 'next0', 'next1', 'next2', 'flag3'], 'p'); // 112
        this.connectState(['root', 'next0', 'next1', 'next2', { array: 'items3', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // 113
        this.subscribeState(['root', 'next0', 'next1', 'next2', 'next3', 'tag4'], v => {}); // 114
        this.subscribeState(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: 0 }, 'name'], v => {}); // 115
        this.connectState(['root', 'next0', 'next1', 'next2', 'next3', 'flag4'], 'p'); // 116
        this.connectState(['root', 'next0', 'next1', 'next2', 'next3', { array: 'items4', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // 117
        this.subscribeState(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'tag5'], v => {}); // 118
        this.subscribeState(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'items5', get: 0 }, 'name'], v => {}); // 119
        this.connectState(['root', 'next0', 'next1', 'next2', 'next3', 'next4', 'flag5'], 'p'); // 120
        this.connectState(['root', 'next0', 'next1', 'next2', 'next3', 'next4', { array: 'items5', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // 121
    }
}
