// Generates a synthetic deep state model + ~200 call sites for the type-checker
// performance benchmark. Regenerate with: node type-tests/perf/generate.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

// ── synthetic state: a chain L0..L8 with array branches, optionals, unions,
//    an index signature, and readonly arrays. ~50 named interfaces. ──────────
const DEPTH = 8;
let model = `// AUTO-GENERATED by generate.mjs — do not edit by hand.\n\n`;
model += `export interface Leaf { id: number; label?: string; note?: string; }\n\n`;

// element interfaces used inside arrays at each level
for (let i = 0; i <= DEPTH; i++) {
    model += `export interface Elem${i} {\n`;
    model += `    id: number;\n`;
    model += `    name?: string;\n`;
    model += `    leaf?: Leaf;\n`;
    if (i < DEPTH) model += `    children?: Elem${i + 1}[];\n`;
    model += `}\n\n`;
}

// alt branch for a union-typed property
model += `export interface AltA { kind: 'a'; shared?: string; onlyA?: number; }\n`;
model += `export interface AltB { kind: 'b'; shared?: string; onlyB?: boolean; }\n\n`;

for (let i = DEPTH; i >= 0; i--) {
    model += `export interface Level${i} {\n`;
    model += `    tag${i}: string;\n`;
    model += `    flag${i}: boolean;\n`;
    model += `    opt${i}?: string;\n`;
    model += `    items${i}: Elem${i}[];\n`;
    model += `    roItems${i}: readonly Elem${i}[];\n`;
    model += `    dict${i}: { [key: string]: Elem${i} };\n`;
    model += `    union${i}?: AltA | AltB;\n`;
    if (i < DEPTH) model += `    next${i}?: Level${i + 1};\n`;
    model += `}\n\n`;
}

model += `export interface PerfState {\n    root?: Level0;\n}\n`;
writeFileSync(join(here, 'state.ts'), model);

// ── call sites ───────────────────────────────────────────────────────────
// Build a path prefix that walks `root` down `depth` levels via next<i>.
function chainPrefix(depth) {
    const segs = ['root'];
    for (let i = 0; i < depth; i++) segs.push(`next${i}`);
    return segs; // ends at Level<depth>
}

let calls = `// AUTO-GENERATED by generate.mjs — do not edit by hand.\n`;
calls += `import { LitElementStateService } from '../../src/index';\n`;
calls += `import { PerfState } from './state';\n\n`;
calls += `declare const s: LitElementStateService<PerfState>;\n\n`;

let n = 0;
const q = (arr) => '[' + arr.map(x => `'${x}'`).join(', ') + ']';

// depth 1..6 plain-key leaf reads (valid for subscribe's old 6-cap too)
for (let depth = 0; depth <= 5; depth++) {
    const prefix = chainPrefix(depth);
    calls += `s.subscribe(${q([...prefix, `tag${depth}`])}, v => {}); // ${n++}\n`;
    calls += `s.subscribe(${q([...prefix, `flag${depth}`])}, v => {}); // ${n++}\n`;
    calls += `s.subscribe(${q([...prefix, `opt${depth}`])}, v => {}); // ${n++}\n`;
    calls += `s.get(${q([...prefix, `tag${depth}`])}); // ${n++}\n`;
}

// array selectors (numeric + predicate) at each reachable level, depth <= 5
for (let depth = 0; depth <= 5; depth++) {
    const prefix = chainPrefix(depth);
    const arrSeg = `{ array: 'items${depth}', get: 0 }`;
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, ${arrSeg}], v => {}); // ${n++}\n`;
    const predSeg = `{ array: 'items${depth}', get: (e: { id: number }, i?: number) => e.id === i }`;
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, ${predSeg}], v => {}); // ${n++}\n`;
    // selector then a plain key into the element
    calls += `s.get([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'items${depth}', get: 0 }, 'name']); // ${n++}\n`;
    // readonly array selector
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'roItems${depth}', get: 0 }], v => {}); // ${n++}\n`;
    // index signature
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, 'dict${depth}', 'anykey'], v => {}); // ${n++}\n`;
    // whole array (plain last key)
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, 'items${depth}'], v => {}); // ${n++}\n`;
    // union property
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, 'union${depth}', 'shared'], v => {}); // ${n++}\n`;
}

// deep get calls up to depth 8 (exercises the removed cap; get old-cap was 8)
for (let depth = 6; depth <= 8; depth++) {
    const prefix = chainPrefix(Math.min(depth, DEPTH));
    calls += `s.get(${q([...prefix, `tag${Math.min(depth, DEPTH)}`])}); // ${n++}\n`;
}

// nested array element -> children -> deeper element
for (let depth = 0; depth <= 4; depth++) {
    const prefix = chainPrefix(depth);
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'items${depth}', get: 0 }, { array: 'children', get: 0 }, 'name'], v => {}); // ${n++}\n`;
}

// selector into element -> leaf -> nested leaf key (more distinct deep paths)
for (let depth = 0; depth <= 5; depth++) {
    const prefix = chainPrefix(depth);
    calls += `s.get([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'items${depth}', get: 0 }, 'leaf', 'label']); // ${n++}\n`;
    calls += `s.get([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'roItems${depth}', get: (e: { name?: string }, i?: number) => e.name === 'x' }, 'id']); // ${n++}\n`;
    calls += `s.get([${prefix.map(x => `'${x}'`).join(', ')}, 'dict${depth}', 'k', 'leaf', 'note']); // ${n++}\n`;
    calls += `s.subscribe([${prefix.map(x => `'${x}'`).join(', ')}, 'union${depth}', 'kind'], v => {}); // ${n++}\n`;
}

// LitElementStateful.subscribeState / connectState coverage
calls += `\nimport { LitElementStateful } from '../../src/index';\n`;
calls += `class PerfComp extends LitElementStateful<PerfState> {\n`;
calls += `    p: any;\n`;
calls += `    run() {\n`;
for (let depth = 0; depth <= 5; depth++) {
    const prefix = chainPrefix(depth);
    calls += `        this.subscribeState([${prefix.map(x => `'${x}'`).join(', ')}, 'tag${depth}'], v => {}); // ${n++}\n`;
    calls += `        this.subscribeState([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'items${depth}', get: 0 }, 'name'], v => {}); // ${n++}\n`;
    calls += `        this.connectState([${prefix.map(x => `'${x}'`).join(', ')}, 'flag${depth}'], 'p'); // ${n++}\n`;
    calls += `        this.connectState([${prefix.map(x => `'${x}'`).join(', ')}, { array: 'items${depth}', get: (e: unknown, i?: number) => i === 0 }, 'leaf'], 'p'); // ${n++}\n`;
}
calls += `    }\n}\n`;

writeFileSync(join(here, 'calls.ts'), calls);
console.log(`generated ${n} call sites`);
