// AUTO-GENERATED by generate.mjs — do not edit by hand.

export interface Leaf { id: number; label?: string; note?: string; }

export interface Elem0 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem1[];
}

export interface Elem1 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem2[];
}

export interface Elem2 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem3[];
}

export interface Elem3 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem4[];
}

export interface Elem4 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem5[];
}

export interface Elem5 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem6[];
}

export interface Elem6 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem7[];
}

export interface Elem7 {
    id: number;
    name?: string;
    leaf?: Leaf;
    children?: Elem8[];
}

export interface Elem8 {
    id: number;
    name?: string;
    leaf?: Leaf;
}

export interface AltA { kind: 'a'; shared?: string; onlyA?: number; }
export interface AltB { kind: 'b'; shared?: string; onlyB?: boolean; }

export interface Level8 {
    tag8: string;
    flag8: boolean;
    opt8?: string;
    items8: Elem8[];
    roItems8: readonly Elem8[];
    dict8: { [key: string]: Elem8 };
    union8?: AltA | AltB;
}

export interface Level7 {
    tag7: string;
    flag7: boolean;
    opt7?: string;
    items7: Elem7[];
    roItems7: readonly Elem7[];
    dict7: { [key: string]: Elem7 };
    union7?: AltA | AltB;
    next7?: Level8;
}

export interface Level6 {
    tag6: string;
    flag6: boolean;
    opt6?: string;
    items6: Elem6[];
    roItems6: readonly Elem6[];
    dict6: { [key: string]: Elem6 };
    union6?: AltA | AltB;
    next6?: Level7;
}

export interface Level5 {
    tag5: string;
    flag5: boolean;
    opt5?: string;
    items5: Elem5[];
    roItems5: readonly Elem5[];
    dict5: { [key: string]: Elem5 };
    union5?: AltA | AltB;
    next5?: Level6;
}

export interface Level4 {
    tag4: string;
    flag4: boolean;
    opt4?: string;
    items4: Elem4[];
    roItems4: readonly Elem4[];
    dict4: { [key: string]: Elem4 };
    union4?: AltA | AltB;
    next4?: Level5;
}

export interface Level3 {
    tag3: string;
    flag3: boolean;
    opt3?: string;
    items3: Elem3[];
    roItems3: readonly Elem3[];
    dict3: { [key: string]: Elem3 };
    union3?: AltA | AltB;
    next3?: Level4;
}

export interface Level2 {
    tag2: string;
    flag2: boolean;
    opt2?: string;
    items2: Elem2[];
    roItems2: readonly Elem2[];
    dict2: { [key: string]: Elem2 };
    union2?: AltA | AltB;
    next2?: Level3;
}

export interface Level1 {
    tag1: string;
    flag1: boolean;
    opt1?: string;
    items1: Elem1[];
    roItems1: readonly Elem1[];
    dict1: { [key: string]: Elem1 };
    union1?: AltA | AltB;
    next1?: Level2;
}

export interface Level0 {
    tag0: string;
    flag0: boolean;
    opt0?: string;
    items0: Elem0[];
    roItems0: readonly Elem0[];
    dict0: { [key: string]: Elem0 };
    union0?: AltA | AltB;
    next0?: Level1;
}

export interface PerfState {
    root?: Level0;
}
